/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/theme.ts
 * Command: astryx theme build lib/theme.ts
 * CLI: @astryxdesign/cli@0.6.1
 * Core: @astryxdesign/core@0.6.1
 */

/// <reference path="./ywap-marikina.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const ywapMarikinaTheme: DefinedTheme;
